[workspace]
resolver = "3"
members = [
    "crates/prism-account-wasm",
    "crates/prism-cli",
    "crates/prism-core",
    "crates/prism-rendezvous",
    "crates/prism-secret",
    "crates/prism-stream",
    "crates/prism-tauri",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/aodjo/Prism"

[workspace.dependencies]
prism-core = { path = "crates/prism-core" }
prism-secret = { path = "crates/prism-secret" }
prism-stream = { path = "crates/prism-stream", default-features = false }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
