/**
 * Prism wire format, shared by the Rust data plane and the TypeScript control plane.
 *
 * The layouts implemented here are specified in `docs/wire-format.md` and pinned by
 * `packages/protocol/vectors.json`, which both `cargo test` and `vitest` assert against.
 * Any format change starts by editing the vectors.
 */

export {
  CLOCK_PING_LEN,
  CLOCK_PONG_LEN,
  CONTROL_HEADER_LEN,
  CURSOR_POSITION_LEN,
  AUDIO_HEADER_LEN,
  FEC_HEADER_LEN,
  GOODBYE_LEN,
  MAX_AUDIO_PAYLOAD,
  MAX_FEC_PAYLOAD,
  MAX_PLAINTEXT_SIZE,
  SEAL_OVERHEAD,
  MAX_FIELD_SHARDS,
  Channel,
  ControlType,
  FEEDBACK_FLAGS_RESERVED_MASK,
  FEEDBACK_PACKET_LEN,
  FEEDBACK_WANTS_KEYFRAME,
  INPUT_PACKET_LEN,
  InputKind,
  MouseButton,
  FORMAT_VERSION,
  MAX_PACKET_SIZE,
  MAX_VIDEO_PAYLOAD,
  VIDEO_FLAGS_RESERVED_MASK,
  VIDEO_HEADER_LEN,
  VideoFlags,
  FILE_ANSWER_LEN,
  FILE_ASK_FIXED_LEN,
  FILE_CHUNK_HEADER_LEN,
  FILE_ENTRY_FIXED_LEN,
  FILE_HEADER_LEN,
  FILE_LISTING_FIXED_LEN,
  FILE_OFFER_FIXED_LEN,
  FILE_REPORT_LEN,
  FileRefusal,
  FileType,
  MAX_FILE_NAME,
  MAX_FILE_PAYLOAD,
} from './constants.js';
export { PrismProtocolError } from './errors.js';
export {
  channelOf,
  controlTypeOf,
  decodeAudioPacket,
  decodeClockPing,
  decodeClockPong,
  decodeCursorPosition,
  decodeFecPacket,
  decodeFeedbackPacket,
  decodeGoodbye,
  decodeInputPacket,
  decodeVideoPacket,
  encodeAudioPacket,
  encodeClockPing,
  encodeClockPong,
  encodeCursorPosition,
  encodeFecPacket,
  encodeGoodbye,
  sliceLenOf,
  encodeFeedbackPacket,
  encodeInputPacket,
  encodeVideoPacket,
  decodeFileAnswer,
  decodeFileAsk,
  decodeFileChunk,
  decodeFileList,
  decodeFileListing,
  decodeFileOffer,
  decodeFileReport,
  encodeFileAnswer,
  encodeFileAsk,
  encodeFileChunk,
  encodeFileList,
  encodeFileListing,
  encodeFileOffer,
  encodeFileReport,
  fileTypeOf,
  plainFileName,
} from './packet.js';
export type {
  AudioPacket,
  ClockPing,
  ClockPong,
  CursorPosition,
  FecPacket,
  FeedbackPacket,
  InputEvent,
  InputPacket,
  VideoPacket,
  FileAnswer,
  FileAsk,
  FileChunk,
  FileEntry,
  FileListing,
  FileOffer,
  FileReport,
} from './packet.js';
