/**
 * Builds the dashboard into one module the Worker can import.
 *
 * The page is four files — markup, styles, two scripts — plus the WebAssembly that turns a
 * password into the secret this server recognises. They stay four real files so that an editor
 * treats them as what they are; this collects them into `src/dashboard.ts` so that TypeScript
 * treats them as what the Worker needs, which is strings.
 *
 * Generating a module beats importing the files directly. A relative `import` of `app.js`
 * resolves to the script itself rather than to its text, and no ambient declaration can
 * override that — TypeScript only consults those for non-relative specifiers.
 *
 * Run before every deploy. The Worker serves whatever this last wrote, so a stale copy is a
 * dashboard deriving with yesterday's parameters and nobody being able to sign in.
 *
 * The package script that runs this is called `bundle` and not `build`, deliberately. The root
 * `build` is `pnpm -r build`, which the desktop application's packaging runs — and this needs a
 * `wasm32-unknown-unknown` toolchain that a machine building the application has no reason to
 * have. It is what `src/dashboard.ts` is committed for: a deploy from a machine with no Rust at
 * all still ships a dashboard, and building the application never reaches for a cross target.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** This package, whatever anybody's working directory is. */
const HERE = dirname(dirname(fileURLToPath(import.meta.url)));

/** The repository root. */
const ROOT = dirname(dirname(HERE));

/** Where cargo leaves the compiled derivation. */
const WASM = join(ROOT, 'target/wasm32-unknown-unknown/release/prism_account_wasm.wasm');

/** Cargo is not on `PATH` under every shell that runs a package script. */
const CARGO = process.env.CARGO ?? join(process.env.HOME ?? '', '.cargo/bin/cargo');

execFileSync(
  CARGO,
  ['build', '--package', 'prism-account-wasm', '--target', 'wasm32-unknown-unknown', '--release'],
  { cwd: ROOT, stdio: 'inherit' },
);

/**
 * Reads one of the dashboard's files.
 *
 * @param {string} name - Its name under `browser/`.
 * @returns {string} What is in it.
 */
const read = (name) => readFileSync(join(HERE, 'browser', name), 'utf8');

/**
 * Quotes a file's contents as a JavaScript string literal.
 *
 * A plain quoted string rather than a template literal, because the CSS and the scripts contain
 * backticks and `${`, and a template literal would run them.
 *
 * @param {string} text - The contents.
 * @returns {string} The literal, ready to paste into a module.
 */
const literal = (text) => JSON.stringify(text);

const wasm = readFileSync(WASM);

const module = `/**
 * The dashboard, as the Worker serves it.
 *
 * Generated by \`scripts/build.mjs\` from \`browser/\` — edit those files, not this one. It is
 * committed so that a deploy from a machine without a Rust toolchain still ships a dashboard
 * that matches the API beside it.
 */

/** The page. */
export const HTML = ${literal(read('index.html'))};

/** Its styles. */
export const CSS = ${literal(read('style.css'))};

/** Its screens. */
export const APP = ${literal(read('app.js'))};

/** What those screens are built out of. */
export const UI = ${literal(read('ui.js'))};

/** Which way round it is drawn, decided in the head before anything is painted. */
export const THEME = ${literal(read('theme.js'))};

/**
 * The password derivation, as base64.
 *
 * Decoded once when the Worker starts rather than held as bytes, because a module is text and
 * this is the only way to carry ${wasm.length} bytes of it without a second deployment.
 */
const WASM_BASE64 = ${literal(wasm.toString('base64'))};

/** The same, as the bytes a browser asks for. */
export const WASM: ArrayBuffer = Uint8Array.from(atob(WASM_BASE64), (character) =>
  character.charCodeAt(0),
).buffer as ArrayBuffer;
`;

writeFileSync(join(HERE, 'src/dashboard.ts'), module);

console.log(
  `src/dashboard.ts — ${(module.length / 1024).toFixed(0)} KB ` +
    `(argon2 ${(wasm.length / 1024).toFixed(1)} KB)`,
);
